### ISSUE TITLE
Failed to create pull

### ISSUE THREAD

**Issue by ShakeJunk** [sanghin/masterflipper#2]
```
$ node ./bin/www
21 currencies loaded
1 leagues loaded
Config initialisation finished.
Scraping Incursion...
{ message: 'Failed to create pull.',
  error:
   { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2018-06-04 10:06:68' for column 'expires_at' at row 1
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (/app/node_modules/mysql/lib/Pool.js:199:23)
    at Query (/app/modules/Db/index.js:50:8)
    at Db.Insert (/app/modules/Db/index.js:248:3)
    at CreatePull (/app/modules/PoeTradeScraper/scrape.js:263:6)
    at ScrapeAll (/app/modules/PoeTradeScraper/scrape.js:137:3)
    at ScrapeIfExpired.CheckPull (/app/modules/PoeTradeScraper/scrape.js:231:5)
    at Query.CheckPull.Db.Query [as _callback] (/app/modules/PoeTradeScraper/scrape.js:258:5)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
     code: 'ER_TRUNCATED_WRONG_VALUE',
     errno: 1292,
     sqlMessage: 'Incorrect datetime value: \'2018-06-04 10:06:68\' for column \'expires_at\' at row 1',
     sqlState: '22007',
     index: 0,
     sql: 'INSERT INTO `poe_currency`.`pulls`(`league_id`, `expires_at`) VALUES (1, \'2018-06-04 10:06:68\');' } }
```

1. Installed Docker
2. docker-compose up -d maria_db
3. docker-compose up -d strongbox
4. docker-compose exec strongbox gulp app
5. Set league to Incursion in the leagues table

any help ?

EDIT: Fixed by restarting everything
EDIT_2:![grafik](https://user-images.githubusercontent.com/10758342/40898750-9a3b98b8-67c3-11e8-9a20-224ccc60735a.png) cant click on the boxes and currency_ratio table is empty

**Comment by sanghin** [comment]
Sorry but this is a WIP repo and we will not work on this before end of Incursion league
